import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Inter } from 'next/font/google';

import { getAllFilesMetadata } from '@/lib/mdx';

import { Box, Flex, Text } from '@chakra-ui/react';
const inter = Inter({ subsets: ['latin'] });

export default function Home({ posts }) {
  return (
    <Box w="100vw" h="100vh" px="64" py="16" bg="brand.950">
      <Flex flexDir="column" gap={2}>
        <Text as="h1" color="white" fontWeight="bold" fontSize="4xl">
          Anthony Acosta
        </Text>

        <Text as="h2" color="white" fontWeight="semibold" fontSize="2xl">
          Cibersecurity Student and Software Developer.
        </Text>
      </Flex>

      <Head>
        <title>Anthony Acosta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div>
        {posts.map((post) => (
          <Link
            key={post.slug}
            href={`/${post.slug}`}
            rel="noopener noreferrer"
          >
            <h2>
              {post.title} <span>-&gt;</span>
            </h2>
            <p>{post.date}</p>
          </Link>
        ))}
      </div> */}
    </Box>
  );
}

export async function getStaticProps() {
  const posts = await getAllFilesMetadata();

  console.log(posts);

  return {
    props: { posts },
  };
}
